# Generated by Django 2.2.1 on 2022-09-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_schedule_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
