# Generated by Django 2.2.1 on 2022-08-31 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
