# Generated by Django 2.2.1 on 2022-08-31 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='schedule_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
